version: '3'
services:
  ss:
    build:
      context: .
      dockerfile: Dockerfile.ss-libev
  kcptun:
    image: xtaci/kcptun:v20170904
    command: ./server -t ss:8388 -key "xxxxxx1" -mode fast2  -crypt aes-128  -dscp 46 -mtu 1300
  udp2raw:
    build:
      context: .
      dockerfile: Dockerfile.udp2raw
    command: ./udp2raw -s -kcptun:8855 -r 127.0.0.1:10998 -k "xxxxxxxxx" --raw-mode faketcp
    ports:
    - "10998:10998/udp"
