FROM alpine:3.6 as builder

WORKDIR /

RUN apk add --no-cache gcc musl-dev g++ git make && \
 git clone https://github.com/wangyu-/udp2raw-tunnel.git  && \
 cd udp2raw-tunnel && \
 make

FROM alpine:3.6
COPY --from=builder /udp2raw-tunnel/udp2raw .
